version: '2'
services:

  videofaces-frontend:
    build: frontend/.
    ports:
      - 5000:5000
    env_file: sql.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development


  videofaces-mysql:
    command: --max_allowed_packet=1024M
    build: videofaces-mysql/.
    ports:
      - 3306:3306
    env_file: sql.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videofaces

  backend-rest:
    build: backend-rest/es.um.sisdist.videofaces.backend.Service/.
    ports:
      - 8080:8080
    env_file: sql.env

  videofaces-grpc:
    build: backend-grpc/es.um.sisdist.videofaces.backend.grpc.GrpcServiceImpl/.
    ports:
      - 50051
    env_file: sql.env
